name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build the Docker image
      run: docker build -t php-ci-cd-app .

    # Add this section to run the container in detached mode and stop it after testing
    - name: Run the Docker container
      run: |
        docker run -d --name php-ci-cd-app -p 8080:80 php-ci-cd-app
        sleep 5  # Wait for the container to start
        docker ps  # Verify it's running
        docker stop php-ci-cd-app  # Stop the container after the test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to cPanel (FTP)
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
